theme: jekyll-theme-slate

title: An awesome website!!!
email: 
description: This is the site of axmmisaka. You can find some contact information here.
github_username:  axmmisaka
kramdown:
  input: GFM
