theme: jekyll-theme-slate

title: An awesome website!!!
email: axmaxmaxm3gr AT foxmail DOT com
description: > This is the site of axmmisaka. You can find some contact information here.
github_username:  axmmisaka
kramdown:
  input: GFM
